# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VoteRPC.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VoteRPC.proto',
  package='',
  serialized_pb=_b('\n\rVoteRPC.proto\"T\n\x0eRequestVoteRPC\x12\x0c\n\x04term\x18\x01 \x02(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x02(\t\x12\x1f\n\x17timeStampOnLatestUpdate\x18\x03 \x02(\x03\"x\n\x0fResponseVoteRPC\x12\x0c\n\x04term\x18\x01 \x02(\x05\x12\x35\n\risVoteGranted\x18\x02 \x02(\x0e\x32\x1e.ResponseVoteRPC.IsVoteGranted\" \n\rIsVoteGranted\x12\x07\n\x03YES\x10\x00\x12\x06\n\x02NO\x10\x01\"\x89\x01\n\rVoteRPCPacket\x12\x15\n\runixTimestamp\x18\x01 \x02(\x03\x12)\n\x0erequestVoteRPC\x18\x02 \x01(\x0b\x32\x0f.RequestVoteRPCH\x00\x12+\n\x0fresponseVoteRPC\x18\x03 \x01(\x0b\x32\x10.ResponseVoteRPCH\x00\x42\t\n\x07payload')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RESPONSEVOTERPC_ISVOTEGRANTED = _descriptor.EnumDescriptor(
  name='IsVoteGranted',
  full_name='ResponseVoteRPC.IsVoteGranted',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='YES', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=191,
  serialized_end=223,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEVOTERPC_ISVOTEGRANTED)


_REQUESTVOTERPC = _descriptor.Descriptor(
  name='RequestVoteRPC',
  full_name='RequestVoteRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='RequestVoteRPC.term', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='candidateId', full_name='RequestVoteRPC.candidateId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeStampOnLatestUpdate', full_name='RequestVoteRPC.timeStampOnLatestUpdate', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=101,
)


_RESPONSEVOTERPC = _descriptor.Descriptor(
  name='ResponseVoteRPC',
  full_name='ResponseVoteRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='ResponseVoteRPC.term', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isVoteGranted', full_name='ResponseVoteRPC.isVoteGranted', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSEVOTERPC_ISVOTEGRANTED,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=223,
)


_VOTERPCPACKET = _descriptor.Descriptor(
  name='VoteRPCPacket',
  full_name='VoteRPCPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unixTimestamp', full_name='VoteRPCPacket.unixTimestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestVoteRPC', full_name='VoteRPCPacket.requestVoteRPC', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseVoteRPC', full_name='VoteRPCPacket.responseVoteRPC', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='VoteRPCPacket.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=226,
  serialized_end=363,
)

_RESPONSEVOTERPC.fields_by_name['isVoteGranted'].enum_type = _RESPONSEVOTERPC_ISVOTEGRANTED
_RESPONSEVOTERPC_ISVOTEGRANTED.containing_type = _RESPONSEVOTERPC
_VOTERPCPACKET.fields_by_name['requestVoteRPC'].message_type = _REQUESTVOTERPC
_VOTERPCPACKET.fields_by_name['responseVoteRPC'].message_type = _RESPONSEVOTERPC
_VOTERPCPACKET.oneofs_by_name['payload'].fields.append(
  _VOTERPCPACKET.fields_by_name['requestVoteRPC'])
_VOTERPCPACKET.fields_by_name['requestVoteRPC'].containing_oneof = _VOTERPCPACKET.oneofs_by_name['payload']
_VOTERPCPACKET.oneofs_by_name['payload'].fields.append(
  _VOTERPCPACKET.fields_by_name['responseVoteRPC'])
_VOTERPCPACKET.fields_by_name['responseVoteRPC'].containing_oneof = _VOTERPCPACKET.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['RequestVoteRPC'] = _REQUESTVOTERPC
DESCRIPTOR.message_types_by_name['ResponseVoteRPC'] = _RESPONSEVOTERPC
DESCRIPTOR.message_types_by_name['VoteRPCPacket'] = _VOTERPCPACKET

RequestVoteRPC = _reflection.GeneratedProtocolMessageType('RequestVoteRPC', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTVOTERPC,
  __module__ = 'VoteRPC_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteRPC)
  ))
_sym_db.RegisterMessage(RequestVoteRPC)

ResponseVoteRPC = _reflection.GeneratedProtocolMessageType('ResponseVoteRPC', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEVOTERPC,
  __module__ = 'VoteRPC_pb2'
  # @@protoc_insertion_point(class_scope:ResponseVoteRPC)
  ))
_sym_db.RegisterMessage(ResponseVoteRPC)

VoteRPCPacket = _reflection.GeneratedProtocolMessageType('VoteRPCPacket', (_message.Message,), dict(
  DESCRIPTOR = _VOTERPCPACKET,
  __module__ = 'VoteRPC_pb2'
  # @@protoc_insertion_point(class_scope:VoteRPCPacket)
  ))
_sym_db.RegisterMessage(VoteRPCPacket)


# @@protoc_insertion_point(module_scope)
