# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: work.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AppendEntriesRPC_pb2
import HeartBeatRPC_pb2
import VoteRPC_pb2
import Ping_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='work.proto',
  package='',
  serialized_pb=_b('\n\nwork.proto\x1a\x16\x41ppendEntriesRPC.proto\x1a\x12HeartBeatRPC.proto\x1a\rVoteRPC.proto\x1a\nPing.proto\"\xdf\x01\n\x0bWorkMessage\x12\x15\n\runixTimeStamp\x18\x01 \x02(\x03\x12\x33\n\x13\x61ppendEntriesPacket\x18\x02 \x01(\x0b\x32\x14.AppendEntriesPacketH\x00\x12+\n\x0fheartBeatPacket\x18\x03 \x01(\x0b\x32\x10.HeartBeatPacketH\x00\x12\'\n\rvoteRPCPacket\x18\x04 \x01(\x0b\x32\x0e.VoteRPCPacketH\x00\x12#\n\x0btrivialPing\x18\x05 \x01(\x0b\x32\x0c.PingMessageH\x00\x42\t\n\x07payload')
  ,
  dependencies=[AppendEntriesRPC_pb2.DESCRIPTOR,HeartBeatRPC_pb2.DESCRIPTOR,VoteRPC_pb2.DESCRIPTOR,Ping_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WORKMESSAGE = _descriptor.Descriptor(
  name='WorkMessage',
  full_name='WorkMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unixTimeStamp', full_name='WorkMessage.unixTimeStamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appendEntriesPacket', full_name='WorkMessage.appendEntriesPacket', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heartBeatPacket', full_name='WorkMessage.heartBeatPacket', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voteRPCPacket', full_name='WorkMessage.voteRPCPacket', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trivialPing', full_name='WorkMessage.trivialPing', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='WorkMessage.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=86,
  serialized_end=309,
)

_WORKMESSAGE.fields_by_name['appendEntriesPacket'].message_type = AppendEntriesRPC_pb2._APPENDENTRIESPACKET
_WORKMESSAGE.fields_by_name['heartBeatPacket'].message_type = HeartBeatRPC_pb2._HEARTBEATPACKET
_WORKMESSAGE.fields_by_name['voteRPCPacket'].message_type = VoteRPC_pb2._VOTERPCPACKET
_WORKMESSAGE.fields_by_name['trivialPing'].message_type = Ping_pb2._PINGMESSAGE
_WORKMESSAGE.oneofs_by_name['payload'].fields.append(
  _WORKMESSAGE.fields_by_name['appendEntriesPacket'])
_WORKMESSAGE.fields_by_name['appendEntriesPacket'].containing_oneof = _WORKMESSAGE.oneofs_by_name['payload']
_WORKMESSAGE.oneofs_by_name['payload'].fields.append(
  _WORKMESSAGE.fields_by_name['heartBeatPacket'])
_WORKMESSAGE.fields_by_name['heartBeatPacket'].containing_oneof = _WORKMESSAGE.oneofs_by_name['payload']
_WORKMESSAGE.oneofs_by_name['payload'].fields.append(
  _WORKMESSAGE.fields_by_name['voteRPCPacket'])
_WORKMESSAGE.fields_by_name['voteRPCPacket'].containing_oneof = _WORKMESSAGE.oneofs_by_name['payload']
_WORKMESSAGE.oneofs_by_name['payload'].fields.append(
  _WORKMESSAGE.fields_by_name['trivialPing'])
_WORKMESSAGE.fields_by_name['trivialPing'].containing_oneof = _WORKMESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['WorkMessage'] = _WORKMESSAGE

WorkMessage = _reflection.GeneratedProtocolMessageType('WorkMessage', (_message.Message,), dict(
  DESCRIPTOR = _WORKMESSAGE,
  __module__ = 'work_pb2'
  # @@protoc_insertion_point(class_scope:WorkMessage)
  ))
_sym_db.RegisterMessage(WorkMessage)


# @@protoc_insertion_point(module_scope)
